version: '3'
services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - ./app/mysql:/var/lib/mysql
  prestashop:
    container_name: prestashop
    image: gurespex/cp-shop:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_FOLDER_ADMIN: administation
      PS_FOLDER_INSTALL: installation
    networks:
      - prestashop_network
    volumes:
      - type: bind
        source: ./app/modules/testModule
        target: /var/www/html/modules/testModule # To develop modules
      - type: bind
        source: ./app/themes/myTheme
        target: /var/www/html/themes/myTheme # To develop themes
      - type: bind
        source: ./app/img
        target: /var/www/html/img # To store image data
      - psdata:/var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - prestashop_network
networks:
  prestashop_network:
volumes:
  psdata: